services:
  db:
    image: postgres:16
    container_name: postgres_studyplan_api
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - app/config/.env

volumes:
  pgdata: